absl/strings/internal/str_format/extension.h: add missing <stdint.h> include
Without the change absl-cpp build fails on this week's gcc-13 snapshot as:

    /build/abseil-cpp/absl/strings/internal/str_format/extension.h:34:33: error: found ':' in nested-name-specifier, expected '::'
       34 | enum class FormatConversionChar : uint8_t;
          |                                 ^
          |                                 ::